"""Pinecone db to store embeddings generated by Vertex ai"""
from pinecone import Pinecone, ServerlessSpec
from config import PINECONE_API_KEY, PINECONE_INDEX_NAME, PINECONE_DIMENSION, PINECONE_METRIC, PINECONE_CLOUD, PINECONE_REGION
import logging
from models import MetaDataFilter

logger = logging.getLogger(__name__)

class VectorStore:
    def __init__(self):
        try:
            self.pinecone_client = Pinecone(PINECONE_API_KEY)
            self._ensure_index_exists()
            self.index = self.pinecone_client.Index(PINECONE_INDEX_NAME)
            logger.info(f"Connected to pinecone index: {PINECONE_INDEX_NAME}")
        except Exception as e:
            logger.error(f"Failed to connect to Pinecone: {e}", exc_info=True)
            raise   # should fail without pinecone
    
    def _ensure_index_exists(self):
        if not self.pinecone_client.has_index(PINECONE_INDEX_NAME):
            self.pinecone_client.create_index(
                name=PINECONE_INDEX_NAME,
                dimension=PINECONE_DIMENSION,
                metric=PINECONE_METRIC,
                spec=ServerlessSpec(cloud=PINECONE_CLOUD, region=PINECONE_REGION)
            )

    def upload_to_pinecone(self, vectors):
        try:
            self.index.upsert(vectors=vectors)
            logger.info("vectors uploaded to Pinecone db")
        except Exception as e:
            logger.error(f"Failed to upload embeddings to Pinecone: {e}", exc_info=True)
            raise

    def filter_existing_vectors(self, chunks):
        try:
            ids = [chunk["id"] for chunk in chunks]
            existing_chunks = self.index.fetch(ids=ids)
            if existing_chunks.get("vectors", None):
                logger.info(f"chunks already in pinecone: {existing_chunks["vectors"].keys()}")  #tesssssssssst
            return [chunk for chunk in chunks if chunk["id"] not in existing_chunks.get("vectors", {})] 
        except Exception as e:
            logger.warning(f"Failed to fetch existing vectors from pinecone: {e}")
            return chunks
    
    def get_similar(self, vector: list[float], metadata_filter: MetaDataFilter | None):
        """Similarity Search against Pinecone vector db"""
        try:
            pinecone_filter = None
            if metadata_filter:
                pinecone_filter = self._create_pinecone_filter(metadata_filter)
            results = self.index.query(
                vector=vector,
                top_k=5,    # currently not much in the db so keep it low to avoid getting irrelevant data
                include_metadata=True,
                filter=pinecone_filter
            )

            # filter out irrelevant chunks
            MIN_SIMILARITY = 0.7
            similar_results = [result for result in results["matches"] if result["score"] >= MIN_SIMILARITY]

            return similar_results
        except Exception as e:
            logger.error(f"Error querying pinecone db: {e}", exc_info=True)
            raise

    def _create_pinecone_filter(self, metadata_filter: MetaDataFilter):
        return {
            metadata_filter.key: {
                f"${metadata_filter.operation}": metadata_filter.value
            }
        }
